### ISSUE TITLE
The problem of not fount files during testing

### ISSUE THREAD

**Issue by zcy1996** [jiny2001/deeply-recursive-cnn-tf#11]
When I test with a trained model, I use the command: python test.py --dataSet14 --inference_depth 9 --feature_num 96 has the following error

Features:96 Inference Depth:9 Initial LR:0.00100 [model_F96_D9_LR0.001000]
(3, 3, 1, 96)-864, (96,)-96, (3, 3, 96, 96)-82944, (96,)-96, (3, 3, 96, 96)-82944, (96,)-96, (3, 3, 96, 96)-82944, (96,)-96, (3, 3, 97, 1)-873, (1,)-1, (9,)-9,
Total 11 variables, 250,963 params
Model restored.
Traceback (most recent call last):
  File "test.py", line 82, in <module>
    if __name__ == '__main__':
  File "C:\Users\lenovo\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "test.py", line 78, in main
    model.init_all_variables(load_initial_data=FLAGS.load_model)
  File "E:\程序\deeply-recursive-cnn-tf-master\super_resolution.py", line 446, in do_super_resolution
    org_image = util.load_image(file_path)
  File "E:\程序\deeply-recursive-cnn-tf-master\super_resolution_utilty.py", line 205, in load_image
    raise LoadError("File not found [%s]" % filename)
super_resolution_utilty.LoadError: File not found []

**Comment by jiny2001** [comment]
Hi, can you try like this? I guess new tensorflow has different arg parser.

python test.py --data=set14 --inference_depth=9 --feature_num=96

**Comment by zcy1996** [comment]
Hello, thank you very much for your reply.I'm sorry to bother you.I also have some questions need to be consulted. The program can't be tested.
When I run with your command, the following results appear：
(base) E:\程序\deeply-recursive-cnn-tf-master>python test.py --data = Set14 --inference_depth = 9 --feature_num = 96
Traceback (most recent call last):
  File "C:\Users\lenovo\AppData\Roaming\Python\Python36\site-packages\absl\flags\_flag.py", line 181, in _parse
    return self.parser.parse(argument)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python36\site-packages\absl\flags\_argument_parser.py", line 152, in parse
    val = self.convert(argument)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python36\site-packages\absl\flags\_argument_parser.py", line 265, in convert
    return int(argument, base)
ValueError: invalid literal for int() with base 10: '='

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 82, in <module>
    if __name__ == '__main__':
  File "C:\Users\lenovo\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\platform\app.py", line 119, in run
    argv = flags.FLAGS(_sys.argv if argv is None else argv, known_only=True)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\platform\flags.py", line 112, in __call__
    return self.__dict__['__wrapped'].__call__(*args, **kwargs)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python36\site-packages\absl\flags\_flagvalues.py", line 626, in __call__
    unknown_flags, unparsed_args = self._parse_args(args, known_only)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python36\site-packages\absl\flags\_flagvalues.py", line 774, in _parse_args
    flag.parse(value)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python36\site-packages\absl\flags\_flag.py", line 166, in parse
    self.value = self._parse(argument)
  File "C:\Users\lenovo\AppData\Roaming\Python\Python36\site-packages\absl\flags\_flag.py", line 184, in _parse
    'flag --%s=%s: %s' % (self.name, argument, e))
absl.flags._exceptions.IllegalFlagValueError: flag --inference_depth==: invalid literal for int() with base 10: '='
